git:
    depth: false # It is not performed any git operation. So, it is only required the last/current commit

before_cache:
    - rm -rf $HOME/.cache/electron-builder/wine

# Cache will not work as expected. Check https://github.com/travis-ci/travis-ci/issues/8519 and the documentation linked
cache:
    directories:
        - $HOME/.npm
        - node_modules
        - $HOME/.cache/electron
        - $HOME/.cache/electron-builder

jobs:
    include:
        - stage: lint
          language: node_js
          node_js: "10"
          install: npm ci
          script: npm run lint -s

        - stage: build-macos
          os: osx
          osx_image: xcode9.4
          env:
              - ELECTRON_CACHE=$HOME/.cache/electron
              - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
          language: node_js
          node_js: "10"
          install: npm ci
          script: npm run electron-build-unpacked

        - stage: build-linux-windows
          os: linux
          services: docker
          language: generic
          install: skip
          script:
              - |
                docker run --rm \
                  -v ${PWD}:/project \
                  -v ~/.cache/electron:/root/.cache/electron \
                  -v ~/.cache/electron-builder:/root/.cache/electron-builder \
                  electronuserland/builder:wine \
                  /bin/bash -c "npm ci && npm run electron-build-unpacked -- --linux --win"
