git:
    depth: false # It is not performed any git operation. So, it is only required the last/current commit

before_cache:
    - rm -rf $HOME/.cache/electron-builder/wine

cache:
    directories:
        - $HOME/.npm
        - node_modules
        - $HOME/.cache/electron
        - $HOME/.cache/electron-builder

jobs:
    include:
        - stage: lint
          language: node_js
          node_js: "10"
          env: CACHE_NAME=shared-cache
          install: npm ci # Install node_modules and cache to use on later stages
          script: npm run lint -s

        - stage: build-macos
          os: osx
          osx_image: xcode9.4
          env: # Cache electron-builder to be faster on later stages
              - ELECTRON_CACHE=$HOME/.cache/electron
              - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
              - CACHE_NAME=shared-cache
          language: node_js
          node_js: "10"
          install: skip
          script: npm run electron-build-unpacked

        - stage: build-linux-windows
          os: linux
          services: docker
          language: generic
          env: CACHE_NAME=shared-cache
          install: skip
          script:
              - |
                docker run --rm \
                  -v ${PWD}:/project \
                  -v ~/.cache/electron:/root/.cache/electron \
                  -v ~/.cache/electron-builder:/root/.cache/electron-builder \
                  electronuserland/builder:wine \
                  /bin/bash -c "npm run electron-build-unpacked -- --linux --win"
